import React, { useState, useEffect } from 'react'
import { Link, useLocation } from 'wouter'

// ─── Report Share Modal ───────────────────────────────────────────────────────
function ReportModal({ booking, onClose }) {
  const [downloading, setDownloading] = useState(false);
  const [sent, setSent] = useState(null);

  const reportText = `
*JeevanCare — Health Report*
━━━━━━━━━━━━━━━━━━━━━━━━
👤 Patient: ${booking.name}
🧪 Service: ${booking.serviceType}
📅 Date: ${booking.preferredDate}
🕐 Time: ${booking.preferredTime}
✅ Status: Completed

Thank you for choosing JeevanCare.
For queries: support@jeevancare.com
  `.trim();

  const handleWhatsApp = () => {
    const encoded = encodeURIComponent(reportText);
    window.open(`https://wa.me/?text=${encoded}`, '_blank');
    setSent('whatsapp');
  };

  const handleEmail = () => {
    const subject = encodeURIComponent(`JeevanCare Report — ${booking.serviceType}`);
    const body = encodeURIComponent(reportText);
    window.open(`mailto:?subject=${subject}&body=${body}`, '_blank');
    setSent('email');
  };

  const handleDownload = () => {
    setDownloading(true);
    const content = `
JEEVANCARE — HEALTH DIAGNOSTIC REPORT
=====================================

Patient Name  : ${booking.name}
Email         : ${booking.email}
Phone         : ${booking.phone || 'N/A'}

Service       : ${booking.serviceType}
Date          : ${booking.preferredDate}
Time Slot     : ${booking.preferredTime}
Status        : ✓ COMPLETED

Address       : ${booking.address}

Notes         : ${booking.notes || 'None'}

=====================================
Report generated by JeevanCare
For support: support@jeevancare.com | +91 9876543210
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `JeevanCare_Report_${booking.serviceType.replace(/\s+/g, '_')}_${booking.preferredDate}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    setTimeout(() => { setDownloading(false); setSent('download'); }, 600);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4" style={{background: 'rgba(0,0,0,0.6)'}}>
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-md overflow-hidden animate-fade-in">

        {/* Header */}
        <div className="bg-gradient-to-r from-green-500 to-teal-600 p-6 text-white relative">
          <button onClick={onClose} className="absolute top-4 right-4 text-white/80 hover:text-white text-2xl leading-none">×</button>
          <div className="text-4xl mb-2">📋</div>
          <h2 className="text-xl font-bold">Report Ready!</h2>
          <p className="text-green-100 text-sm mt-1">Choose how you'd like to receive your report</p>
        </div>

        {/* Booking Summary */}
        <div className="bg-gray-50 px-6 py-4 border-b">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-full bg-green-100 flex items-center justify-center text-green-600 font-bold text-sm">✓</div>
            <div>
              <p className="font-semibold text-gray-800 text-sm">{booking.serviceType}</p>
              <p className="text-gray-500 text-xs">{booking.preferredDate} • {booking.preferredTime}</p>
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="p-6 space-y-3">

          {/* WhatsApp */}
          <button
            onClick={handleWhatsApp}
            className="w-full flex items-center gap-4 p-4 rounded-xl border-2 border-green-200 hover:border-green-400 hover:bg-green-50 transition-all group"
          >
            <div className="w-12 h-12 rounded-full bg-green-500 flex items-center justify-center text-white text-xl flex-shrink-0 group-hover:scale-110 transition-transform">
              💬
            </div>
            <div className="text-left">
              <p className="font-semibold text-gray-800">Send via WhatsApp</p>
              <p className="text-gray-500 text-xs">Share report summary instantly</p>
            </div>
            {sent === 'whatsapp' && <span className="ml-auto text-green-500 text-sm font-medium">Sent ✓</span>}
          </button>

          {/* Email */}
          <button
            onClick={handleEmail}
            className="w-full flex items-center gap-4 p-4 rounded-xl border-2 border-blue-200 hover:border-blue-400 hover:bg-blue-50 transition-all group"
          >
            <div className="w-12 h-12 rounded-full bg-blue-500 flex items-center justify-center text-white text-xl flex-shrink-0 group-hover:scale-110 transition-transform">
              ✉️
            </div>
            <div className="text-left">
              <p className="font-semibold text-gray-800">Send via Email</p>
              <p className="text-gray-500 text-xs">Opens your mail app with report</p>
            </div>
            {sent === 'email' && <span className="ml-auto text-blue-500 text-sm font-medium">Opened ✓</span>}
          </button>

          {/* Download */}
          <button
            onClick={handleDownload}
            disabled={downloading}
            className="w-full flex items-center gap-4 p-4 rounded-xl border-2 border-purple-200 hover:border-purple-400 hover:bg-purple-50 transition-all group disabled:opacity-60"
          >
            <div className="w-12 h-12 rounded-full bg-purple-500 flex items-center justify-center text-white text-xl flex-shrink-0 group-hover:scale-110 transition-transform">
              ⬇️
            </div>
            <div className="text-left">
              <p className="font-semibold text-gray-800">Download Report</p>
              <p className="text-gray-500 text-xs">Save as .txt file to your device</p>
            </div>
            {sent === 'download' && <span className="ml-auto text-purple-500 text-sm font-medium">Saved ✓</span>}
          </button>
        </div>

        {/* Footer */}
        <div className="px-6 pb-6">
          <button onClick={onClose} className="w-full py-2 text-gray-500 hover:text-gray-700 text-sm font-medium transition-colors">
            Close
          </button>
        </div>
      </div>
    </div>
  );
}

// ─── Main Home Dashboard ──────────────────────────────────────────────────────
function Home() {
  const [, navigate] = useLocation();
  const [bookings, setBookings] = useState([]);
  const [showTests, setShowTests] = useState(false);
  const [showPackages, setShowPackages] = useState(false);
  const [showCompleted, setShowCompleted] = useState(false);
  const [loading, setLoading] = useState(true);
  const [selectedReport, setSelectedReport] = useState(null);

  const fetchUserStats = async () => {
    try {
      const token = localStorage.getItem('userToken');
      if (!token) return;
      const response = await fetch('${import.meta.env.VITE_API_URL}/api/bookings/my-bookings', {
        headers: { 'Authorization': `Bearer ${token}`, 'Content-Type': 'application/json' }
      });
      if (response.ok) setBookings(await response.json());
    } catch (e) {
      console.error("Error fetching stats:", e);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { fetchUserStats(); }, []);

  // Derived counts
  const testBookings     = bookings.filter(b => b.bookingType !== 'package');
  const packageBookings  = bookings.filter(b => b.bookingType === 'package');
  const completedAll     = bookings.filter(b => b.status === 'Completed');

  const handleLogout = async () => {
    await fetch('${import.meta.env.VITE_API_URL}/api/auth/logout', { method: 'POST', credentials: 'include' });
    localStorage.removeItem('userToken');
    navigate('/');
    window.location.reload();
  };

  const closeAllPanels = () => { setShowTests(false); setShowPackages(false); setShowCompleted(false); };

  const BookingTable = ({ rows, emptyMsg }) => (
    rows.length === 0
      ? <p className="p-6 text-gray-500 text-center">{emptyMsg}</p>
      : (
        <table className="w-full text-left">
          <thead className="bg-gray-50 text-gray-500 uppercase text-xs">
            <tr>
              <th className="px-6 py-3">Service</th>
              <th className="px-6 py-3">Date</th>
              <th className="px-6 py-3">Time</th>
              <th className="px-6 py-3">Status</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-100">
            {rows.map(b => (
              <tr key={b._id} className="hover:bg-gray-50">
                <td className="px-6 py-4 font-medium text-gray-900">
                  {b.services && b.services.length > 0
                    ? <div className="flex flex-wrap gap-1">
                        {b.services.map((s, idx) => (
                          <span key={idx} className="inline-flex items-center text-xs bg-blue-50 text-blue-700 px-2 py-0.5 rounded-full">{s.name}</span>
                        ))}
                      </div>
                    : <span>{b.serviceType}</span>
                  }
                </td>
                <td className="px-6 py-4 text-gray-500">{b.preferredDate}</td>
                <td className="px-6 py-4 text-gray-500">{b.preferredTime}</td>
                <td className="px-6 py-4">
                  <span className={`px-2 py-1 rounded-full text-xs font-semibold ${b.status === 'Completed' ? 'bg-green-100 text-green-700' : 'bg-yellow-100 text-yellow-700'}`}>
                    {b.status}
                  </span>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )
  );

  return (
    <div className="min-h-screen bg-gray-50">

      {/* Report Modal */}
      {selectedReport && <ReportModal booking={selectedReport} onClose={() => setSelectedReport(null)} />}

      {/* Navbar */}
      <nav className="bg-white shadow-lg">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-16">
            <h1 className="text-2xl font-bold text-blue-600">JeevanCare</h1>
            <div className="flex space-x-3">
              <Link href="/tests"><button className="bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700 text-sm">View Tests</button></Link>
              <Link href="/packages"><button className="bg-green-600 text-white px-4 py-2 rounded-md hover:bg-green-700 text-sm">View Packages</button></Link>
              <Link href="/book-home-visit"><button className="bg-purple-600 text-white px-4 py-2 rounded-md hover:bg-purple-700 text-sm">Book Home Visit</button></Link>
              <button onClick={handleLogout} className="bg-red-500 text-white px-4 py-2 rounded-md hover:bg-red-600 text-sm">Logout</button>
            </div>
          </div>
        </div>
      </nav>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">

        <div className="mb-8">
          <h2 className="text-3xl font-bold text-gray-900">Welcome to Your Dashboard</h2>
          <p className="text-gray-500 mt-1">Track your health journey with JeevanCare</p>
        </div>

        {/* Quick Actions */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
          <Link href="/tests">
            <div className="bg-white p-6 rounded-xl shadow hover:shadow-md cursor-pointer border-l-4 border-blue-500 transition-all hover:-translate-y-0.5">
              <h3 className="text-lg font-semibold text-blue-600 mb-1">Browse Tests</h3>
              <p className="text-gray-500 text-sm">Find and book individual lab tests</p>
            </div>
          </Link>
          <Link href="/packages">
            <div className="bg-white p-6 rounded-xl shadow hover:shadow-md cursor-pointer border-l-4 border-green-500 transition-all hover:-translate-y-0.5">
              <h3 className="text-lg font-semibold text-green-600 mb-1">Health Packages</h3>
              <p className="text-gray-500 text-sm">Comprehensive health checkup packages</p>
            </div>
          </Link>
        </div>

        {/* ── STAT CARDS ── */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">

          {/* Card 1 — Tests Booked */}
          <div
            onClick={() => { const open = !showTests; closeAllPanels(); setShowTests(open); }}
            className={`p-6 rounded-xl shadow cursor-pointer border-2 transition-all hover:-translate-y-0.5 ${showTests ? 'border-blue-500 bg-blue-50' : 'bg-white border-transparent hover:border-blue-300'}`}
          >
            <div className="flex items-center justify-between mb-3">
              <div className="w-10 h-10 rounded-full bg-blue-100 flex items-center justify-center text-xl">🧪</div>
              {!loading && <span className="text-xs font-medium text-blue-500 bg-blue-100 px-2 py-0.5 rounded-full">{testBookings.filter(b=>b.status==='Pending').length} pending</span>}
            </div>
            <div className="text-3xl font-bold text-blue-600">{loading ? "..." : testBookings.length}</div>
            <div className="text-gray-600 font-medium mt-1">Tests Booked</div>
            <p className="text-xs text-blue-400 mt-2">{showTests ? "▲ Hide details" : "▼ View all tests"}</p>
          </div>

          {/* Card 2 — Packages Booked */}
          <div
            onClick={() => { const open = !showPackages; closeAllPanels(); setShowPackages(open); }}
            className={`p-6 rounded-xl shadow cursor-pointer border-2 transition-all hover:-translate-y-0.5 ${showPackages ? 'border-green-500 bg-green-50' : 'bg-white border-transparent hover:border-green-300'}`}
          >
            <div className="flex items-center justify-between mb-3">
              <div className="w-10 h-10 rounded-full bg-green-100 flex items-center justify-center text-xl">📦</div>
              {!loading && <span className="text-xs font-medium text-green-500 bg-green-100 px-2 py-0.5 rounded-full">{packageBookings.filter(b=>b.status==='Pending').length} pending</span>}
            </div>
            <div className="text-3xl font-bold text-green-600">{loading ? "..." : packageBookings.length}</div>
            <div className="text-gray-600 font-medium mt-1">Packages Booked</div>
            <p className="text-xs text-green-400 mt-2">{showPackages ? "▲ Hide details" : "▼ View all packages"}</p>
          </div>

          {/* Card 3 — Reports Ready */}
          <div
            onClick={() => { const open = !showCompleted; closeAllPanels(); setShowCompleted(open); }}
            className={`p-6 rounded-xl shadow cursor-pointer border-2 transition-all hover:-translate-y-0.5 ${showCompleted ? 'border-teal-500 bg-teal-50' : 'bg-white border-transparent hover:border-teal-300'}`}
          >
            <div className="flex items-center justify-between mb-3">
              <div className="w-10 h-10 rounded-full bg-teal-100 flex items-center justify-center text-xl">📋</div>
              {!loading && completedAll.length > 0 && (
                <span className="text-xs font-medium text-teal-600 bg-teal-100 px-2 py-0.5 rounded-full animate-pulse">New</span>
              )}
            </div>
            <div className="text-3xl font-bold text-teal-600">{loading ? "..." : completedAll.length}</div>
            <div className="text-gray-600 font-medium mt-1">Reports Ready</div>
            <p className="text-xs text-teal-400 mt-2">{showCompleted ? "▲ Hide details" : "▼ Get your reports"}</p>
          </div>
        </div>

        {/* ── DETAIL PANELS ── */}

        {/* Tests Detail */}
        {showTests && (
          <div className="mt-6 bg-white rounded-xl shadow-lg overflow-hidden border border-gray-100">
            <div className="bg-blue-600 px-6 py-3 flex justify-between items-center">
              <h3 className="text-white font-semibold">Your Test Bookings ({testBookings.length})</h3>
              <button onClick={() => setShowTests(false)} className="text-white/70 hover:text-white text-xl">×</button>
            </div>
            <BookingTable rows={testBookings} emptyMsg="No tests booked yet. Head to Browse Tests to get started!" />
          </div>
        )}

        {/* Packages Detail */}
        {showPackages && (
          <div className="mt-6 bg-white rounded-xl shadow-lg overflow-hidden border border-gray-100">
            <div className="bg-green-600 px-6 py-3 flex justify-between items-center">
              <h3 className="text-white font-semibold">Your Package Bookings ({packageBookings.length})</h3>
              <button onClick={() => setShowPackages(false)} className="text-white/70 hover:text-white text-xl">×</button>
            </div>
            <BookingTable rows={packageBookings} emptyMsg="No packages booked yet. Explore our Health Packages!" />
          </div>
        )}

        {/* Reports Ready Detail */}
        {showCompleted && (
          <div className="mt-6 bg-white rounded-xl shadow-lg overflow-hidden border border-gray-100">
            <div className="bg-gradient-to-r from-teal-500 to-green-600 px-6 py-4 flex justify-between items-center">
              <div>
                <h3 className="text-white font-semibold text-lg">Reports Ready</h3>
                <p className="text-teal-100 text-xs mt-0.5">Click on any report below to share or download</p>
              </div>
              <button onClick={() => setShowCompleted(false)} className="text-white/70 hover:text-white text-2xl">×</button>
            </div>

            {completedAll.length === 0 ? (
              <div className="p-8 text-center">
                <div className="text-5xl mb-3">🔬</div>
                <p className="text-gray-500">No completed tests yet.</p>
                <p className="text-gray-400 text-sm mt-1">Reports will appear here once your technician marks them complete.</p>
              </div>
            ) : (
              <div className="p-4 grid gap-3">
                {completedAll.map(b => (
                  <div
                    key={b._id}
                    onClick={() => setSelectedReport(b)}
                    className="flex items-center justify-between p-4 rounded-xl border-2 border-gray-100 hover:border-teal-300 hover:bg-teal-50 cursor-pointer transition-all group"
                  >
                    <div className="flex items-center gap-4">
                      <div className="w-11 h-11 rounded-full bg-green-100 flex items-center justify-center text-green-600 font-bold text-sm">✓</div>
                      <div>
                        <p className="font-semibold text-gray-800">{b.serviceType}</p>
                        <p className="text-gray-400 text-xs mt-0.5">{b.preferredDate} • {b.preferredTime}</p>
                      </div>
                    </div>
                    <div className="flex items-center gap-2">
                      <span className="text-xs bg-green-100 text-green-700 px-2 py-1 rounded-full font-medium">Completed</span>
                      <span className="text-teal-500 group-hover:translate-x-1 transition-transform text-lg">→</span>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        )}

      </div>
    </div>
  );
}

export default Home;
